const ALL_SCHEMES = [
{id:"pmmy_shishu_small",name:"PMMY Shishu Below 20k",min:1,max:19999,keys:["vendor","all"],score:96,ministry:"DFS",reason:"Best for very small {amount} for {biz} - instant approval."},
{id:"pmmy_shishu",name:"PMMY Shishu ₹20k-50k",min:20000,max:50000,keys:["tailor","vendor","all"],score:95,ministry:"DFS",reason:"No.1 micro loan for {biz} needing {amount} - no collateral."},
{id:"pmmy_kishor",name:"PMMY Kishor ₹50k-5L",min:50001,max:500000,keys:["shop","manufacturing","all"],score:92,ministry:"DFS",reason:"For growing {biz} needing {amount}."},
{id:"pmmy_tarun",name:"PMMY Tarun ₹5L-10L",min:500001,max:1000000,keys:["all"],score:88,ministry:"DFS",reason:"For established {biz} needing {amount}."},
{id:"pmegp",name:"PMEGP 15-35% Subsidy",min:50000,max:2500000,keys:["manufacturing","all"],score:89,ministry:"MSME",reason:"Subsidy 15-35% for new {biz} with {amount}."},
{id:"cgtmse",name:"CGTMSE Collateral Free",min:100000,max:50000000,keys:["all"],score:86,ministry:"MSME",reason:"No collateral for {amount} - Govt guarantee up to 5 Cr."},
{id:"standup",name:"Stand-Up India ₹10L-1Cr",min:1000000,max:10000000,keys:["women","sc","st","all"],score:91,ministry:"DFS",reason:"₹10L-1Cr for SC/ST & Women for {biz}."},
{id:"vishwakarma",name:"PM Vishwakarma",min:10000,max:300000,keys:["artisan","tailor","carpenter","all"],score:93,ministry:"MSME",reason:"Toolkit + loan up to 3L for {biz}."},
{id:"pm_svanidhi",name:"PM SVANidhi Street Vendors",min:10000,max:50000,keys:["vendor","all"],score:95,ministry:"MoHUA",reason:"₹50k collateral-free for {biz}."},
{id:"zed",name:"MSME ZED Certification",min:50000,max:5000000,keys:["manufacturing","export","all"],score:90,ministry:"MSME",reason:"Best for Domestic Manufacturer aiming to export {biz} with {amount}."},
{id:"kcc",name:"KCC Allied",min:10000,max:300000,keys:["farmer","dairy","all"],score:87,ministry:"Agriculture",reason:"4% credit for {biz} with {amount}."},
{id:"seed",name:"Startup India Seed Fund",min:500000,max:5000000,keys:["startup","all"],score:90,ministry:"DPIIT",reason:"Seed fund up to 50L for {biz}."},
{id:"mahila",name:"Mahila Udyam Nidhi",min:10000,max:1000000,keys:["women","tailor","all"],score:92,ministry:"SIDBI",reason:"Special loan for women {biz}."},
{id:"svep",name:"SVEP Village",min:10000,max:200000,keys:["rural","all"],score:84,ministry:"MoRD",reason:"Rural non-farm {biz} via SHG."},
{id:"sfurti",name:"SFURTI Cluster",min:500000,max:5000000,keys:["artisan","cluster","all"],score:85,ministry:"MSME",reason:"Cluster development for {biz}."},
{id:"aspire",name:"ASPIRE Rural Incubation",min:50000,max:2000000,keys:["rural","startup","all"],score:83,ministry:"MSME",reason:"Incubation for rural {biz}."},
{id:"clcss",name:"CLCSS Tech Subsidy 15%",min:100000,max:10000000,keys:["manufacturing","all"],score:86,ministry:"MSME",reason:"15% tech subsidy for {biz}."},
{id:"cdp",name:"MSE-CDP Infra",min:1000000,max:20000000,keys:["cluster","manufacturing","all"],score:82,ministry:"MSME",reason:"Infra support for {biz} cluster."},
{id:"scst_hub",name:"National SC-ST Hub",min:50000,max:5000000,keys:["sc","st","all"],score:88,ministry:"MSME",reason:"Special support for SC/ST {biz}."},
{id:"treds",name:"TReDS Bill Discounting",min:10000,max:5000000,keys:["all"],score:80,ministry:"MSME",reason:"Instant payment for MSME {biz}."},
{id:"gem",name:"GeM Sahay",min:10000,max:1000000,keys:["all"],score:81,ministry:"Commerce",reason:"Govt marketplace credit for {biz}."},
{id:"champions",name:"CHAMPIONS Portal",min:10000,max:5000000,keys:["all"],score:84,ministry:"MSME",reason:"Grievance + credit for {biz}."},
{id:"ramp",name:"RAMP Program",min:500000,max:10000000,keys:["all"],score:85,ministry:"MSME",reason:"World Bank aided for {biz}."},
{id:"sri",name:"SRI Fund ₹50k Cr",min:5000000,max:50000000,keys:["all"],score:87,ministry:"MSME",reason:"Equity infusion for {biz}."},
{id:"psb59",name:"PSB Loans 59 Mins",min:100000,max:5000000,keys:["all"],score:90,ministry:"DFS",reason:"Approval in 59 mins for {biz}."},
{id:"nsfdc",name:"NSFDC SC Loan",min:50000,max:3000000,keys:["sc","all"],score:86,ministry:"Social Justice",reason:"Concessional loan for SC {biz}."},
{id:"nskfdc",name:"NSKFDC Safai Karamchari",min:50000,max:2000000,keys:["sc","all"],score:84,ministry:"Social Justice",reason:"For Safai Karamchari {biz}."},
{id:"nbcfdc",name:"NBCFDC OBC Loan",min:50000,max:3000000,keys:["obc","all"],score:85,ministry:"Social Justice",reason:"For OBC {biz}."},
{id:"nhfdc",name:"NHFDC Divyangjan",min:50000,max:5000000,keys:["divyang","all"],score:86,ministry:"Social Justice",reason:"For Divyangjan {biz}."},
{id:"nmdfc",name:"NMDFC Minority",min:50000,max:3000000,keys:["minority","all"],score:85,ministry:"Minority",reason:"For Minority {biz}."},
{id:"nstfdc",name:"NSTFDC ST Loan",min:50000,max:3000000,keys:["st","all"],score:86,ministry:"Tribal",reason:"For ST {biz}."},
{id:"pmfme",name:"PMFME Micro Food",min:50000,max:1000000,keys:["food","all"],score:88,ministry:"Food Processing",reason:"35% subsidy for food {biz}."},
{id:"ahidf",name:"AHIDF Dairy & Animal",min:100000,max:50000000,keys:["dairy","farmer","all"],score:87,ministry:"Animal Husbandry",reason:"3% subvention for dairy {biz}."},
{id:"aif",name:"Agriculture Infra Fund",min:100000,max:20000000,keys:["farmer","all"],score:86,ministry:"Agriculture",reason:"3% subvention for farm infra {biz}."},
{id:"pmmsy",name:"PM Matsya Sampada",min:50000,max:5000000,keys:["fishery","farmer","all"],score:84,ministry:"Fisheries",reason:"For fishery {biz}."},
{id:"nrlm",name:"DAY-NRLM SHG Loan",min:10000,max:500000,keys:["women","shg","rural","all"],score:90,ministry:"MoRD",reason:"SHG loan up to 5L for women {biz}."},
{id:"nulm",name:"DAY-NULM Urban",min:10000,max:500000,keys:["urban","vendor","all"],score:85,ministry:"MoHUA",reason:"Urban self-employment {biz}."},
{id:"eclgs",name:"ECLGS Emergency Credit",min:100000,max:50000000,keys:["all"],score:82,ministry:"DFS",reason:"Emergency credit 100% guarantee for {biz}."},
{id:"startup_credit",name:"Credit Guarantee for Startups",min:500000,max:50000000,keys:["startup","all"],score:88,ministry:"DPIIT",reason:"Guarantee for startup {biz}."},
{id:"sidbi_smile",name:"SIDBI SMILE",min:1000000,max:25000000,keys:["manufacturing","all"],score:87,ministry:"SIDBI",reason:"Soft loan for Make in India {biz}."},
{id:"samridhi",name:"Mahila Samridhi Yojana",min:10000,max:140000,keys:["women","sc","all"],score:86,ministry:"NSFDC",reason:"For SC women {biz}."},
{id:"pm_daksh",name:"PM DAKSH Skill Loan",min:10000,max:1000000,keys:["sc","obc","all"],score:83,ministry:"Social Justice",reason:"Skill + loan for {biz}."},
{id:"epcg",name:"EPCG Zero Duty Export",min:100000,max:50000000,keys:["export","manufacturing","all"],score:89,ministry:"Commerce",reason:"Zero duty import for export {biz}."},
{id:"advance_auth",name:"Advance Authorisation",min:100000,max:50000000,keys:["export","manufacturing","all"],score:88,ministry:"Commerce",reason:"Duty free import for exporter {biz}."},
{id:"pmegp_rural",name:"PMEGP Rural 35% Subsidy",min:50000,max:2500000,keys:["rural","all"],score:90,ministry:"MSME",reason:"35% subsidy in rural for {biz} with {amount}."},
{id:"pmegp_urban",name:"PMEGP Urban 25% Subsidy",min:50000,max:2500000,keys:["urban","all"],score:88,ministry:"MSME",reason:"25% subsidy in urban for {biz}."},
{id:"coir_vikas",name:"Coir Vikas Yojana",min:10000,max:1000000,keys:["artisan","all"],score:82,ministry:"MSME",reason:"Coir business support for {biz}."},
{id:"coir_udyami",name:"Coir Udyami Yojana",min:50000,max:1000000,keys:["artisan","all"],score:83,ministry:"MSME",reason:"Coir unit setup for {biz}."},
{id:"gramodyog",name:"Gramodyog Vikas",min:10000,max:500000,keys:["rural","artisan","all"],score:81,ministry:"MSME",reason:"Village industry for {biz}."},
{id:"kvic_honey",name:"Honey Mission",min:10000,max:500000,keys:["farmer","all"],score:84,ministry:"MSME",reason:"Beekeeping for {biz} with {amount}."},
{id:"kvic_kumhar",name:"Kumhar Sashaktikaran",min:10000,max:500000,keys:["artisan","all"],score:82,ministry:"MSME",reason:"Potter support for {biz}."},
{id:"leather",name:"Leather Tech - FLCTD",min:100000,max:10000000,keys:["manufacturing","all"],score:83,ministry:"MSME",reason:"Leather & footwear tech for {biz}."},
{id:"esdp",name:"ESDP Entrepreneurship Skill",min:10000,max:1000000,keys:["all"],score:80,ministry:"MSME",reason:"Skill + startup for {biz}."},
{id:"imc",name:"International Cooperation",min:100000,max:5000000,keys:["export","all"],score:84,ministry:"MSME",reason:"Export market support for {biz}."},
{id:"mpda",name:"Marketing Promotion",min:10000,max:1000000,keys:["all"],score:81,ministry:"MSME",reason:"Marketing help for {biz}."},
{id:"procurement",name:"Public Procurement Policy",min:10000,max:50000000,keys:["all"],score:85,ministry:"MSME",reason:"25% govt purchase from {biz}."},
{id:"samarth",name:"Samarth - Textile",min:10000,max:1000000,keys:["tailor","textile","all"],score:86,ministry:"Textiles",reason:"Textile skill + loan for {biz}."},
{id:"sitat",name:"SITP Textile Park",min:1000000,max:50000000,keys:["textile","manufacturing","all"],score:82,ministry:"Textiles",reason:"Textile park infra for {biz}."},
{id:"atuf",name:"ATUFS Textile Upgrade",min:100000,max:20000000,keys:["textile","all"],score:83,ministry:"Textiles",reason:"15% capital subsidy for textile {biz}."},
{id:"nttm",name:"National Technical Textile Mission",min:500000,max:10000000,keys:["textile","manufacturing","all"],score:84,ministry:"Textiles",reason:"Technical textile for {biz}."},
{id:"livestock",name:"National Livestock Mission",min:50000,max:5000000,keys:["dairy","farmer","all"],score:85,ministry:"Animal Husbandry",reason:"Livestock startup for {biz}."},
{id:"dairy_fpo",name:"Dairy FPO - NABARD",min:100000,max:10000000,keys:["dairy","farmer","all"],score:86,ministry:"NABARD",reason:"Dairy FPO support for {biz}."},
{id:"fpo",name:"FPO Formation 10k FPOs",min:100000,max:10000000,keys:["farmer","all"],score:87,ministry:"Agriculture",reason:"FPO grant + credit for {biz}."},
{id:"pmkisan_fpo",name:"PM Kisan FPO Loan",min:50000,max:5000000,keys:["farmer","all"],score:85,ministry:"Agriculture",reason:"Credit to FPO farmers {biz}."},
{id:"agriclinics",name:"Agri-Clinics Agri-Business",min:100000,max:2000000,keys:["farmer","startup","all"],score:84,ministry:"Agriculture",reason:"Agri-business for {biz}."},
{id:"tide",name:"TIDE 2.0 Incubation",min:100000,max:2000000,keys:["startup","all"],score:87,ministry:"MeitY",reason:"Incubation for tech {biz}."},
{id:"samridh",name:"SAMRIDH Startup",min:500000,max:40000000,keys:["startup","all"],score:88,ministry:"MeitY",reason:"Matching fund for startup {biz}."},
{id:"sisfs_inc",name:"SISFS Incubator",min:500000,max:5000000,keys:["startup","all"],score:86,ministry:"DPIIT",reason:"Incubator seed for {biz}."},
{id:"fund_funds",name:"Fund of Funds for Startups",min:1000000,max:100000000,keys:["startup","all"],score:89,ministry:"DPIIT",reason:"VC fund for {biz}."},
{id:"credit_guarantee_trust",name:"CGTMSE 2.0 - 85% Guarantee",min:100000,max:50000000,keys:["all"],score:87,ministry:"MSME",reason:"85% guarantee cover for {biz} with {amount}."},
{id:"pradhan_mantri_rojgar",name:"PMRPY Employer Incentive",min:10000,max:1000000,keys:["all"],score:80,ministry:"Labour",reason:"Employer subsidy for {biz} hiring."},
{id:"skill_india_loan",name:"Skill Loan Scheme",min:5000,max:150000,keys:["all"],score:81,ministry:"Skill India",reason:"Skill course loan for {biz}."},
{id:"pm_yuva",name:"PM YUVA Entrepreneurship",min:10000,max:1000000,keys:["student","all"],score:82,ministry:"MSME",reason:"Entrepreneurship for student {biz}."},
{id:"digital_msme",name:"Digital MSME",min:10000,max:1000000,keys:["all"],score:83,ministry:"MSME",reason:"Digital adoption subsidy for {biz}."},
{id:"lean",name:"MSME Lean Scheme",min:100000,max:10000000,keys:["manufacturing","all"],score:84,ministry:"MSME",reason:"Lean manufacturing for {biz}."},
{id:"ip_trust",name:"MSME IP - Patent Reimburse",min:10000,max:1000000,keys:["startup","manufacturing","all"],score:85,ministry:"MSME",reason:"Patent cost reimburse for {biz}."},
{id:"incubation_msme",name:"MSME Incubation Idea",min:100000,max:1500000,keys:["startup","all"],score:86,ministry:"MSME",reason:"Idea to prototype ₹15L for {biz}."},
{id:"design",name:"MSME Design - 75% Grant",min:100000,max:4000000,keys:["manufacturing","all"],score:84,ministry:"MSME",reason:"Design improvement grant for {biz}."},
{id:"wps",name:"Women Entrepreneurship Platform",min:10000,max:1000000,keys:["women","all"],score:88,ministry:"NITI",reason:"WEP support for women {biz}."},
{id:"mahila_coir",name:"Mahila Coir Yojana",min:10000,max:500000,keys:["women","artisan","all"],score:85,ministry:"MSME",reason:"Coir training + stipend for women {biz}."},
{id:"ai_udyam",name:"AI for Entrepreneurship - Udyam",min:10000,max:5000000,keys:["all"],score:86,ministry:"MSME",reason:"Udyam registration benefits for {biz}."},
{id:"export_promo",name:"MSME Export Promotion",min:100000,max:5000000,keys:["export","all"],score:85,ministry:"MSME",reason:"Export promo grant for {biz}."},
{id:"domestic_market",name:"Domestic Market Development",min:50000,max:2000000,keys:["manufacturing","all"],score:83,ministry:"MSME",reason:"Domestic market support for {biz} aiming to go national."},
{id:"oyi",name:"One Year Incubation - OYI",min:50000,max:2000000,keys:["startup","all"],score:82,ministry:"MSME",reason:"One year support for {biz}."},
{id:"credit_linked",name:"Credit Linked Capital Subsidy 2.0",min:100000,max:10000000,keys:["manufacturing","all"],score:87,ministry:"MSME",reason:"Capital subsidy 2.0 for {biz} with {amount}."},
{id:"msme_mart",name:"mSME Mart - B2B",min:10000,max:1000000,keys:["all"],score:80,ministry:"MSME",reason:"B2B marketplace for {biz}."},
{id:"government_emarketplace",name:"GeM Startup Runway",min:10000,max:1000000,keys:["startup","all"],score:81,ministry:"Commerce",reason:"Govt buying from startup {biz}."},
{id:"nsp",name:"National SC Plan - 100% Subsidy Tool",min:10000,max:500000,keys:["sc","all"],score:86,ministry:"MSME",reason:"Tool kit for SC {biz}."},
{id:"tribal_25",name:"Tribal Co-op Marketing",min:50000,max:5000000,keys:["st","all"],score:84,ministry:"Tribal",reason:"Tribal product marketing for {biz}."},
{id:"minority_udyam",name:"Minority Udyam - Nai Roshni",min:10000,max:500000,keys:["minority","women","all"],score:83,ministry:"Minority",reason:"Leadership + loan for minority women {biz}."},
{id:"naps",name:"NAPS Apprenticeship Stipend",min:10000,max:1000000,keys:["all"],score:80,ministry:"Skill India",reason:"Stipend support for {biz} hiring apprentices."},
{id:"pmegp_second",name:"PMEGP Second Loan Upto 1Cr",min:100000,max:10000000,keys:["all"],score:85,ministry:"MSME",reason:"Second expansion loan up to 1Cr for {biz}."}
];
function analyzeStory(){
  const text=document.getElementById('userInput').value.trim(); if(!text){alert("Type your situation!");return;}
  const lower=text.toLowerCase(); let need=0, amount="Not found";
  let m2=text.match(/(\d+(\.\d+)?)\s*lakh/i); if(m2){need=parseFloat(m2[1])*100000; amount="₹"+m2[0];} else{let all=[...text.matchAll(/₹?\s*(\d{1,3},?\d{3,5})/g)]; if(all.length){let v=parseInt(all[all.length-1][0].replace(/,/g,'')); if(v>1000){need=v; amount="₹"+v.toLocaleString('en-IN');}}}
  let biz="Small Business", bizKey="all";
  if(lower.includes("mobile")){biz="Mobile repair shop";bizKey="mobile";} else if(lower.includes("tailor")){biz="Tailoring business";bizKey="tailor";} else if(lower.includes("food")||lower.includes("vendor")){biz="Food vending";bizKey="food";} else if(lower.includes("manufacturing")||lower.includes("export")||lower.includes("domestic manufacturer")){biz="Manufacturing unit";bizKey="manufacturing";} else if(lower.includes("shop")){biz="Small Shop";bizKey="shop";}
  let scored=ALL_SCHEMES.map(s=>{let score=s.minAmount<=need&&need<=s.maxAmount?s.baseScore:s.baseScore-30; if(s.bestFor.includes(bizKey)||s.bestFor.includes("all"))score+=5; if((lower.includes("export")||lower.includes("domestic manufacturer"))&&s.id==="zed")score+=15; if(lower.includes("vendor")&&s.id==="pm_svanidhi")score+=12; if(score>98)score=98; return{...s,score,reason:s.reason.replace("{amount}",amount).replace("{biz}",biz)};});
  scored.sort((a,b)=>b.score-a.score); let top3=scored.slice(0,3);
  localStorage.setItem("selectedScheme",top3[0].name); localStorage.setItem("subsidy",top3[0].name.includes("PMEGP")?"35%":"15%"); localStorage.setItem("loanAmount",need||50000); localStorage.setItem("businessType",biz);
  let html=`<div style="margin-top:15px"><h3>✅ Extracted: ${biz} | ${amount}</h3>`;
  top3.forEach(s=>{html+=`<div class="scheme" style="background:${s.score>=90?'#eafff0':'#eaf0ff'};border-left:4px solid ${s.score>=90?'green':'#3b82f6'}"><b>${s.name} - ${s.score}% Match</b><br><small>${s.ministry}</small><br>${s.reason}<br><small>📄 ${s.docs}</small></div>`;});
  html+=`<button onclick="location.href='modelB.html'" style="background:#28a745">Go to Model B → Calculator</button> <button onclick="location.href='modelC.html'" style="background:#7c3aed">Go to Model C → Map</button></div>`;
  document.getElementById('resultBox').innerHTML=html;
}
